### ISSUE TITLE
[MOBILE_TESTING] - Pembayaran H+1 setelah permohonan

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#1]
waktu pembayaran terlalu lama/tidak ada fitur untuk langsung bayar menggunakan wallet
![image](https://user-images.githubusercontent.com/39518178/40899233-1e060382-67f0-11e8-9d39-09fc863288a4.png)

**Comment by chelsymooy** [comment]
Closed,
@viviramadyah bisa recheck

**Comment by viviramadyah** [comment]
diclose besok, mau nunggu potongan saldo otomatis sesuai jadwal

**Comment by viviramadyah** [comment]
Close, next case
https://github.com/ThunderID/GantiRugi.com/issues/21
