### ISSUE TITLE
[MOBILE WEB_TESTING] - Link Asuransi

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#11]
ada 2 fitur pilihan asuransi dengan 2 tampilan berbeda, tapi intinya sama aja.
tampilan yang paling atas ada 4 menu jenis asuransi seperti versi mobile
![image](https://user-images.githubusercontent.com/39518178/41016369-16821526-6979-11e8-9ee4-a042fd36da63.png)

dibawahnya, ada pilihan 4 asuransi juga cuma beda tampilan dan sedikit keterangan, kalau diklik balik lagi ke atas
![image](https://user-images.githubusercontent.com/39518178/41016415-5d29c6f4-6979-11e8-8f0e-d6472ce43302.png)

**Comment by agilma** [comment]
https://github.com/erickmo/GantiRugi/tree/1fa25134eb7c38acf0ded12515b7071c26b26d04

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/41889721-3b9eb7ac-7936-11e8-97f9-1e57ffd8ca96.png)
