### ISSUE TITLE
[MOBILE_TESTING] - Display klaim berjalan blank

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#13]
ada 1 klaim berjalan, ketika di klik halaman blank, untuk check status terakhir mesti klik menu tab "semua" dulu.
![image](https://user-images.githubusercontent.com/39518178/41074249-4deda1b6-6a31-11e8-9848-6fa94d852658.png)
![image](https://user-images.githubusercontent.com/39518178/41074257-59aaf8a0-6a31-11e8-8d24-d619cbc7b2bd.png)

**Comment by budi7** [comment]
fixed on v 2.5.2
- remove detail option since no grouping options

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/41078331-51705cb0-6a46-11e8-8aef-165393e71cfc.png)
