### ISSUE TITLE
[MOBILE_TESTING] - Record klaim nol

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#14]
Status klaim masih baru approved, berarti masih berjalan. tapi record summarynya sudah nol
![image](https://user-images.githubusercontent.com/39518178/41074330-d58bd138-6a31-11e8-9ca6-1bb31010ebc5.png)
![image](https://user-images.githubusercontent.com/39518178/41074452-71bdcd40-6a32-11e8-81b2-b7438e11c71e.png)

ketika di klik **detail** 
![image](https://user-images.githubusercontent.com/39518178/41074406-347d6850-6a32-11e8-8392-aff96721a071.png)

ketika diklik tab **Semua**
![image](https://user-images.githubusercontent.com/39518178/41074429-518ad72a-6a32-11e8-93ee-fd5a8ea32b0d.png)

**Comment by budi7** [comment]
Fixed on update v2.5.2
- update filter klaim

*jumlah klaim berjalan : API calculation recheck

**Comment by viviramadyah** [comment]
updated, harusnya "Klaim Berjalan" ada 3
![image](https://user-images.githubusercontent.com/39518178/41078396-ca277512-6a46-11e8-90c1-f800f7fc3432.png)
![image](https://user-images.githubusercontent.com/39518178/41078379-abc166e6-6a46-11e8-8b5e-98ffb597dd7c.png)
![image](https://user-images.githubusercontent.com/39518178/41078386-baf220ba-6a46-11e8-9f5f-b9f0890d3f66.png)

**Comment by chelsymooy** [comment]
Close ya @viviramadyah

**Comment by viviramadyah** [comment]
well done
![image](https://user-images.githubusercontent.com/39518178/41079294-759cf8c8-6a4b-11e8-9646-70e36fad0185.png)
