### ISSUE TITLE
[MOBILE_TESTING] - Lampiran Polis untuk Teman

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#15]
pendaftaran polis untuk "teman"
![image](https://user-images.githubusercontent.com/39518178/41074941-a0256cae-6a34-11e8-8cd9-b9490ae48096.png)

Lampiran dokumen fotonya, default Vivi Ramadyah
![image](https://user-images.githubusercontent.com/39518178/41074978-c1d593e2-6a34-11e8-9bd6-a7ae05a9cba4.png)

Diklik untuk ganti foto KTP, bisa dan berhasil ke capture
![image](https://user-images.githubusercontent.com/39518178/41074996-d7db33b8-6a34-11e8-8d78-7b13211a3fb6.png)

Klik "Unggah" untuk upload foto, langsung logout
![image](https://user-images.githubusercontent.com/39518178/41075014-ec4f3be6-6a34-11e8-98c8-7ce475198ab0.png)

tapi fotonya sudah ke save di hp
![image](https://user-images.githubusercontent.com/39518178/41075174-a8758db6-6a35-11e8-8fc1-5695279a6dad.png)

**Comment by budi7** [comment]
Fixed on version 2.5.2
- tweak memory efficiency on taking photo
- set default "foto KTP" only for me

**Comment by viviramadyah** [comment]
well done
![image](https://user-images.githubusercontent.com/39518178/41078426-f3396b36-6a46-11e8-9d45-389cf5daccf0.png)
