### ISSUE TITLE
[MOBILE_TESTING] - Status Dompet

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#16]
Status widthdrawl, request belum di proses sudah complete 
![image](https://user-images.githubusercontent.com/39518178/41078624-118bfc2e-6a48-11e8-859f-3578570f2309.png)

dan record "On Hold" masih nol
![image](https://user-images.githubusercontent.com/39518178/41078576-d67a110c-6a47-11e8-9983-005b7f2515e8.png)

**Comment by chelsymooy** [comment]
mobile

**Comment by chelsymooy** [comment]
Setelah permintaan withdraw, laman dompet tidak di refresh @viviramadyah

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/41079198-e303fcaa-6a4a-11e8-8313-7174bd9dba35.png)

**Comment by budi7** [comment]
fixed on v2.5.2
- add "on_hold" local data 
- refresh data after transaction
