### ISSUE TITLE
[MOBILE_TESTING] - Perlengkapan Tambahan Asuransi Mobil

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#17]
1 : input nama item eksterior
![image](https://user-images.githubusercontent.com/39518178/41082776-9f1f8f90-6a59-11e8-9e4a-8f5c04c08700.png)

2 : input harga dan nama item eksterior hilang
![image](https://user-images.githubusercontent.com/39518178/41082826-bee416c0-6a59-11e8-91ec-6db1ec077efd.png)

3 : input lagi nama item eksterior, tanpa ubah harga dan langsung klik button tambah
![image](https://user-images.githubusercontent.com/39518178/41082854-d4bc3c7a-6a59-11e8-973b-0704cf940b5f.png)

4. setelah klik button "tambah", nama item eksterior kehapus dengan warning "input harus diisi"
![image](https://user-images.githubusercontent.com/39518178/41082885-f0e64e36-6a59-11e8-81df-e780977a55ac.png)

**Comment by budi7** [comment]
fixed on 2.5.4 
- add parameter to select plugin

**Comment by viviramadyah** [comment]
well done
![image](https://user-images.githubusercontent.com/39518178/41147496-bca11b42-6b30-11e8-81b0-f49d194544ab.png)
