### ISSUE TITLE
[MOBILE WEB_TESTING] - Konten belum

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#18]
konten alur klaim belum di update
![image](https://user-images.githubusercontent.com/39518178/41084258-cb1ea91a-6a5d-11e8-942e-fea56d9bfa88.png)

**Comment by chelsymooy** [comment]
otewe

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/41889773-855468e2-7936-11e8-92a4-43641135c443.png)
