### ISSUE TITLE
[MOBILE_TESTING] - display menu klaim beda sama klaim di home

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#20]
Status klaim berjalan ada 3, tapi klaim berjalan di home hanya tampil 1. Mungkin judul di home bisa diganti "Berkas Klaim" aja, disamakan seperti Berkas Polis yg dihome dengan summary klaim berjalan dan klaim closed ditambah button Lihat semua klaim 

atau di tambah Detail> seperti berkas permohonan

![image](https://user-images.githubusercontent.com/39518178/41084752-2fc54440-6a5f-11e8-99c1-f10facd2f864.png)
![image](https://user-images.githubusercontent.com/39518178/41084650-f947d702-6a5e-11e8-98e9-278fabcc46b3.png)
![image](https://user-images.githubusercontent.com/39518178/41084887-8b978ff8-6a5f-11e8-82f4-68050806ee63.png)

**Comment by chelsymooy** [comment]
ini sudah kayaknya @viviramadyah
