### ISSUE TITLE
[MOBILE_TESTING] - Saldo belum terpotong otomatis

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#21]
Status request yang menunggu pembayaran sudah pindah ke menunggu persetujuan (artinya sudah bayar), tapi saldo belum terpotong
![image](https://user-images.githubusercontent.com/39518178/41134926-2b2b8d64-6af9-11e8-92a0-dec651afee54.png)
![image](https://user-images.githubusercontent.com/39518178/41134933-3713ab5c-6af9-11e8-8772-8d2f3b434e60.png)

**Comment by chelsymooy** [comment]
coba di test yang live, @viviramadyah 

Di testing schedulenya lagi masalah

**Comment by viviramadyah** [comment]
done
