### ISSUE TITLE
[MOBILE WEB_TESTING] - Berkas Permohonan Aktif dan Tidak Aktif

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#26]
Di web mobile ada, tambahan summary Berkas Permohonan Aktif dan Tidak Aktif
![image](https://user-images.githubusercontent.com/39518178/41137329-d0314820-6b04-11e8-9b00-324e6d6ff24f.png)

tapi versi mobile apps, tidak ada
![image](https://user-images.githubusercontent.com/39518178/41137405-2be013d6-6b05-11e8-8603-8907d118272c.png)

**Comment by agilma** [comment]
f8f196934d278ea463e5cc56e7629bf7772a2ba4

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/41889874-154b8f02-7937-11e8-8da4-bf8949229beb.png)
