### ISSUE TITLE
[MOBILE_TESTING] - Upload Foto (live app)

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#27]
1. Applikasi GantiRugi Live, ini foto ke-3 yang akan di upload
![image](https://user-images.githubusercontent.com/39518178/41138259-390714ba-6b0a-11e8-9da6-7647caedd314.png)

2. Setelah klik upload
![image](https://user-images.githubusercontent.com/39518178/41138264-487311ce-6b0a-11e8-8484-35679177f160.png)

**Comment by chelsymooy** [comment]
bisa coba lagi @viviramadyah

**Comment by viviramadyah** [comment]
done -> live app

![image](https://user-images.githubusercontent.com/39518178/41151339-acc2de40-6b3a-11e8-879e-e5e4865eeb09.png)
