### ISSUE TITLE
[WEB_TESTING] - Sub Menu Klaim Member

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#4]
Sub menu Klaim berdasarkan member belum bisa diklik.
![image](https://user-images.githubusercontent.com/39518178/40910179-a9ae712e-6815-11e8-812d-15f4feb1ce57.png)

**Comment by chelsymooy** [comment]
closed, bisa di cek @viviramadyah

**Comment by viviramadyah** [comment]
closed
![image](https://user-images.githubusercontent.com/39518178/41029436-d43d971c-69a5-11e8-8326-6122d2fd8ef5.png)
