### ISSUE TITLE
[MOBILE_TESTING] - Asuransi Mobil belum bisa klik Beli Asuransi

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#5]
Asuransi Mobil belum bisa pengajuan Beli Asuransi. Asuransi Niaga dan motor juga belum ada datanya
![image](https://user-images.githubusercontent.com/39518178/40952551-ddb0e28c-68a5-11e8-8710-af359db2738d.png)
![image](https://user-images.githubusercontent.com/39518178/40952557-e772614c-68a5-11e8-9ae7-4cbe98dd5329.png)

**Comment by chelsymooy** [comment]
Premi mobil closed @viviramadyah 
Motor & niaga pending

**Comment by viviramadyah** [comment]
closed
![image](https://user-images.githubusercontent.com/39518178/41028935-ab809d52-69a4-11e8-8a51-ed4857af2634.png)
