### ISSUE TITLE
[MOBILE_TESTING] - Asuransi Kecelakaan Diri

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#6]
ketika pengajuan gantirugi sudah ditolak, dari history pengajuan dipoint ke-3 ada 'Pengajuan' dan button "Ajukan Ulang". Ketika diklik ajukan ulang (dropdown menu tidak bisa diklik).
 
![image](https://user-images.githubusercontent.com/39518178/40952771-d800a2cc-68a6-11e8-80bb-9380787d3fed.png)

**Comment by budi7** [comment]
fixed on 2.5.2
- repair module preload
