### ISSUE TITLE
[MOBILE_TESTING] - History Dompet

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#8]
Double history dalam 1 transaksi.
![image](https://user-images.githubusercontent.com/39518178/40966999-2e60798c-68dc-11e8-9643-49bba630e2f4.png)

**Comment by chelsymooy** [comment]
Fix @viviramadyah

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/41073558-0b5ec210-6a2e-11e8-89b0-150b1824dd85.png)
