### ISSUE TITLE
[MOBILE WEB_TESTING] - Design Interface 

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GantiRugi.com#9]
Nama member dan level tabrakan sama icon profil
![image](https://user-images.githubusercontent.com/39518178/41013600-035024b4-6971-11e8-85e0-945f8e040588.png)
![image](https://user-images.githubusercontent.com/39518178/41013623-32a9ae88-6971-11e8-99c1-118f22bf431c.png)

**Comment by chelsymooy** [comment]
mas agil

**Comment by viviramadyah** [comment]
smartphone udah ok, yg belum ok via ipad
![image](https://user-images.githubusercontent.com/39518178/41137774-32e29da0-6b07-11e8-8e53-21897587e5ff.png)
![image](https://user-images.githubusercontent.com/39518178/41137787-3f91d728-6b07-11e8-8027-f415845c0598.png)

**Comment by agilma** [comment]
https://github.com/erickmo/GantiRugi/tree/d2848ece9a5cd33dbb8d69168e17c63a34dd326b

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/41889432-da4e35b4-7934-11e8-8db7-b749879ae228.png)
![image](https://user-images.githubusercontent.com/39518178/41889440-e4f87f9c-7934-11e8-8157-e313f16991bc.png)
